web:
  image: chrisss404/opencart:latest-php5.5
  links:
    - db
  ports:
    - "80:80"
  environment:
    - SHOP_ADMIN_USER=joe1
    - SHOP_ADMIN_PASSWORD=abc123
    - VIRTUAL_HOST=localhost
db:
  image: chrisss404/opencart:latest-mysql5.5