language: python
python: "3.6"
addons:
  chrome: stable
  firefox: latest
install:
  - pip install nose pylint
  - pip install -r requirements.txt
before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
  - install_dir="/usr/local/bin"
  - json=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest)
  - url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux64"))')
  - curl -s -L "$url" | tar -xz
  - chmod +x geckodriver
  - sudo mv geckodriver "$install_dir"
  - echo "installed geckodriver binary in $install_dir"

script:
  - pytest -v -s ./hw1/test*.py
  - pytest -v -s ./hw2/test*.py
  - pytest -v -s ./hw3/test*.py
  - pytest -v -s ./hw4/test*.py
  - pytest -v -s ./hw5/test*.py
  - pylint --disable=C0103,C0111,C0112,W0613,R0801,C0301,R0903,W0104 ./hw*/*.py
