language: python
python: "3.6"
install:
  - pip install nose pylint
  - pip install -r requirements.txt
script:

  - pytest -v -s ./hw*/
  - pylint --disable=C0103,C0111,C0112 ./hw*/*.py
  - pylint --disable=C0103,C0111,C0112 ./hw*/*/*.py