language: python
python: "3.7"
install:
  - pip install nose pylint
  - pip install -r requirements.txt
script:
  - pytest -v -s hw1/*
  - pytest -v -s hw2/*
  - pylint --disable=C0103,C0111,C0112 */*.py