language: python
python: "3.6"
install:
  - pip install nose pylint
  - pip install -r requirements.txt
script:
  - cd hw1
  - pytest -v -s */*.py
  - pylint --disable=C0103,C0111,C0112 */*.py
  - cd ../hw2
  - pytest -v -s */*.py
  - pylint --disable=C0103,C0111,C0112 */*.py